export { default as heel1} from'./heel1.webp';
export { default as heel2} from'./heel2.webp';
export { default as heel3} from'./heel3.webp';
export { default as heelButtom1} from'./heelButtom1.webp';
export { default as heelButtom2} from'./heelButtom2.webp';
export { default as heelButtom3} from'./heelButtom3.webp';
export { default as heelButtom4} from'./heelButtom4.webp';
export { default as heelButtom5} from'./heelButtom5.webp';
export { default as heelButtom6} from'./heelButtom6.webp';